/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sugery_project;

//TODO set this as the main one?
//TODO add login options

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import sun.security.util.Password;

//how to invoke the other screen once all data gathered?

/**
 *
 * @author mikowhy
 */



public class configJFrame extends javax.swing.JFrame {
//TODO Description of Methods
    //TODO change these to other values? e.g. Integer.MIN_VALUE (?)

private boolean nameOk = false;
private boolean ageOk = false;
private boolean goalOk = false; 
private boolean passOk = false; 
private Hashtable<String, Boolean> tests = new Hashtable<String, Boolean>();
//private List<boolean> checks = new ArrayList<boolean>();
//TODO sql should be its' own class 

    BufferedWriter writer; 
    String username = "";
    private int age = -1;
    private int goal = -1;
    private ArrayList<User> usArr = new ArrayList<User>(); // idt it should be new
    mainFrame mf ;
    private userUtils utils = new userUtils(); 
    private valueVerifier verifier = new valueVerifier();
    //TODO rethink whether this should be an association or composition
    
    
    public configJFrame() {
        initComponents();
//        entryText.setBackground(null);
        nameArea1.requestFocus();
        tests.put("Name", nameOk);
        tests.put("Age", ageOk);
        tests.put("Goal", goalOk);
        tests.put("Password", passOk);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createUsrButton = new javax.swing.JButton();
        goalField = new javax.swing.JScrollPane();
        goalArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ageArea = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        nameArea1 = new javax.swing.JTextArea();
        jTextField8 = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        goBack = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        createUsrButton.setBackground(new java.awt.Color(0, 0, 0));
        createUsrButton.setForeground(new java.awt.Color(255, 255, 255));
        createUsrButton.setText("create a new user");
        createUsrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUsrButtonActionPerformed(evt);
            }
        });
        createUsrButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createUsrButtonKeyPressed(evt);
            }
        });
        getContentPane().add(createUsrButton);
        createUsrButton.setBounds(120, 330, 530, 50);
        createUsrButton.getAccessibleContext().setAccessibleName("apBut1");

        goalField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        goalField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                goalFieldKeyPressed(evt);
            }
        });

        goalArea.setBackground(new java.awt.Color(0, 0, 0));
        goalArea.setColumns(10);
        goalArea.setForeground(new java.awt.Color(255, 255, 255));
        goalArea.setRows(1);
        goalArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                goalAreaKeyPressed(evt);
            }
        });
        goalField.setViewportView(goalArea);

        getContentPane().add(goalField);
        goalField.setBounds(400, 220, 135, 36);

        jScrollPane6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        ageArea.setBackground(new java.awt.Color(0, 0, 0));
        ageArea.setColumns(10);
        ageArea.setForeground(new java.awt.Color(255, 255, 255));
        ageArea.setRows(1);
        ageArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageAreaKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(ageArea);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(200, 220, 135, 36);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Age");
        jTextField5.setFocusable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 260, 46, 24);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 51, 51));
        jTextField7.setFont(new java.awt.Font("Mukta Mahee", 2, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("    But first, introduce yourself.");
        jTextField7.setBorder(null);
        jTextField7.setFocusable(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(140, 40, 480, 100);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Name");
        jTextField6.setFocusable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(60, 260, 50, 24);

        jScrollPane4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        nameArea1.setBackground(new java.awt.Color(0, 0, 0));
        nameArea1.setColumns(10);
        nameArea1.setForeground(new java.awt.Color(255, 255, 255));
        nameArea1.setRows(1);
        nameArea1.setBorder(null);
        nameArea1.setFocusTraversalPolicyProvider(true);
        nameArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameArea1KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(nameArea1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(20, 220, 135, 36);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Goal");
        jTextField8.setFocusable(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(440, 260, 46, 24);

        passField.setBackground(new java.awt.Color(0, 0, 0));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setToolTipText("");
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passField);
        passField.setBounds(590, 220, 135, 40);

        goBack.setBackground(new java.awt.Color(0, 0, 0));
        goBack.setForeground(new java.awt.Color(255, 255, 255));
        goBack.setText("back to login");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack);
        goBack.setBounds(570, 420, 150, 32);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Password");
        jTextField9.setFocusable(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(616, 260, 90, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mikowhy/Documents/Informatyka/Side Projects/Java/Sugery/sugery/sugery_project/src/main/resources/config.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryCreatingUser() throws ClassNotFoundException, SQLException, ParseException{
            
        //TODO text area displays out of bounds
//        if(userCreate()){ // TODO use "try" instead?
          if(validEntriesCheck()){
//              if(!utils.usernameExists(username)){ // bug here
                try{
                  username = nameArea1.getText().replaceAll("\\s+", "");
                  age = Integer.parseInt(ageArea.getText().replaceAll("\\s+",""));
                  goal = Integer.parseInt(goalArea.getText().replaceAll("\\s+",""));
                  utils.addUser(username, age, goal, passField.getPassword());
                  mf = new mainFrame(new User(username, age, goal)); // TODO should there be a new user statement?
                  mf.setVisible(true);
                  this.setVisible(false);
                  mf.displayUserData(); // the most recent one  
                }catch(Exception e){ // list the exceptions here

                }
          }
        }
    private void createUsrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUsrButtonActionPerformed
        try {
            tryCreatingUser(); // not entirely sure this is correct
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_createUsrButtonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void ageAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageAreaKeyPressed
        if (evt.getKeyCode()==9){
            goalArea.requestFocus();
        }
    }//GEN-LAST:event_ageAreaKeyPressed

    private void goalFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goalFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_goalFieldKeyPressed

    private void createUsrButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createUsrButtonKeyPressed
        // TODO add your handling code here:
        if (this.hasFocus() && evt.getKeyCode()==13){
            try { 
                tryCreatingUser();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(configJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createUsrButtonKeyPressed

    private void goalAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goalAreaKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==9){
                    passField.requestFocus();
        }
    }//GEN-LAST:event_goalAreaKeyPressed

    private void nameArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameArea1KeyPressed
            if (evt.getKeyCode()==9){
                   ageArea.requestFocus();
            }

    }//GEN-LAST:event_nameArea1KeyPressed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
            //TODO move focus
        
    }//GEN-LAST:event_passFieldActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        loginScreen lf = new loginScreen();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goBackActionPerformed

    private void passFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldKeyPressed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

   
    boolean validEntriesCheck() throws SQLException{
    //TODO: throw an exception, but don't stop the execution    
        
    //TODO invoke this with "while(!vec()) ?
    //TODO: this check should be more precise (e.g. define the range for age)
    //TODO why is it redefined here btw?      
    
        ArrayList<String> inputs = new ArrayList<String>(); 
        
        
        //TODO need to encode that within the method
        inputs.add(nameArea1.getText().replaceAll("\\s+", ""));
        inputs.add(ageArea.getText().replaceAll("\\s+",""));
        inputs.add(goalArea.getText().replaceAll("\\s+",""));
        inputs.add(passField.getPassword().toString());
        
        return verifier.checkConfigData(inputs); //TODO this should be returned
        
    //setValFalse;
    /*
        for (Entry e: tests.entrySet()) e.setValue(false); // redundant?


            try{
                username = nameArea1.getText().replaceAll("\\s+", "");
                if(!username.equals("")) tests.replace("Name", true); //, goalOk
            }catch(Exception e){
                //JOptionPane.showMessageDialog(new JFrame("Problem"), "Username field empty");
            }
            try{
                age = Integer.parseInt(ageArea.getText().replaceAll("\\s+",""));
                if(age > -1) tests.replace("Age", true);
            }catch(Exception e){
                    //JOptionPane.showMessageDialog(new JFrame("Problem"), "Age field empty?");
            }
            try{
                goal = Integer.parseInt(goalArea.getText().replaceAll("\\s+","")); 
                if(goal > 0) tests.replace("Goal", true); // or display the other error here?
            }catch(Exception e){
                  //JOptionPane.showMessageDialog(new JFrame("Problem"), "Goal field empty");
            }    
            try{
                char[] pass= passField.getPassword();
                if(pass.length > 0) tests.replace("Password", true);
            }catch(Exception e){
                  //JOptionPane.showMessageDialog(new JFrame("Problem"), "Password field empty");
            }
                return (tests.get("Name") && tests.get("Age") && tests.get("Goal") && tests.get("Password"));
    */
            }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(configJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(configJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(configJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(configJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //TODO add the main screen?
                //TODO the login screen should be here?
                new configJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ageArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createUsrButton;
    private javax.swing.JButton goBack;
    private javax.swing.JTextArea goalArea;
    private javax.swing.JScrollPane goalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea nameArea1;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables
}
