/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sugery_project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mikowhy
 */
public class newScoreValue extends javax.swing.JFrame {

    /**
     * Creates new form newScoreValue
     */
    private User user;
    private int score;
    private String date; 
    private entryTable et = new entryTable();
    
    public newScoreValue(User user, int score, String date) {
        //TODO rethink the constructor
        initComponents();
        this.user = user;
        this.score = score;
        this.date = date; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);
        getContentPane().add(scoreField);
        scoreField.setBounds(90, 77, 210, 131);

        jButton1.setText("Set & Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 250, 101, 32);

        jTextField2.setEditable(false);
        jTextField2.setText("Enter New Score Below:");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 30, 300, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // check if score ok
        // execute update
        if(scoreVerify()){
            // first need to find that score 
            String sql = "UPDATE Scores SET score = " + scoreField.getText()
                    + " where username = " + '\'' +  this.user.getName() + "' AND date = '"
                     + this.date + "';";
            
            try {
                et.addRemoveEntry(sql);
            } catch (SQLException ex) {
                Logger.getLogger(newScoreValue.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private boolean scoreVerify(){
        try{
            int score = Integer.parseInt(scoreField.getText());
            if(score > 0) return true;
        }catch (Exception e){
              JOptionPane.showMessageDialog(new JFrame("Error"), "Invalid score value"); 
        }
        JOptionPane.showMessageDialog(new JFrame("Error"), "Invalid score value");  //todo how to replace it?
        return false;
     
        
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField scoreField;
    // End of variables declaration//GEN-END:variables
}
